
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sun Mar 04 04:01:17 EST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRLIT = 5;
  public static final int rw_WHILE = 43;
  public static final int rw_BOOL = 38;
  public static final int LBRACKET = 14;
  public static final int MULTICOM = 45;
  public static final int rw_IF = 30;
  public static final int SLASH = 22;
  public static final int rw_CONTINUE = 40;
  public static final int rw_FALSE = 35;
  public static final int LPAREN = 7;
  public static final int SEMI = 6;
  public static final int rw_PRINT = 42;
  public static final int rw_TRUE = 37;
  public static final int MINUS = 13;
  public static final int RPAREN = 8;
  public static final int NOT = 26;
  public static final int rw_VOID = 41;
  public static final int INTLIT = 3;
  public static final int LT = 17;
  public static final int rw_CONST = 31;
  public static final int COMMA = 20;
  public static final int rw_ELSE = 36;
  public static final int GEQ = 21;
  public static final int PLUS = 12;
  public static final int rw_READ = 33;
  public static final int rw_INT = 34;
  public static final int EOF = 0;
  public static final int RBRACKET = 24;
  public static final int rw_WRITE = 46;
  public static final int error = 1;
  public static final int COR = 28;
  public static final int rw_CLASS = 29;
  public static final int rw_RETURN = 32;
  public static final int EQ = 25;
  public static final int ASG = 9;
  public static final int TIMES = 19;
  public static final int CHARLIT = 4;
  public static final int COLON = 27;
  public static final int LBRACE = 10;
  public static final int rw_CHAR = 44;
  public static final int RBRACE = 11;
  public static final int CAND = 16;
  public static final int LEQ = 18;
  public static final int rw_BREAK = 39;
  public static final int GT = 15;
  public static final int NOTEQ = 23;
  public static final int IDENTIFIER = 2;
}

