
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Feb 23 02:28:14 EST 2012
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 10;
  public static final int LBRACE = 7;
  public static final int ASG = 6;
  public static final int rw_IF = 11;
  public static final int SEMI = 3;
  public static final int PLUS = 9;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RPAREN = 5;
  public static final int IDENTIFIER = 2;
  public static final int RBRACE = 8;
  public static final int LPAREN = 4;
}

